name: Deploy to Openshift

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${github.workflow}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, frontend, migrations]
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          build_context: ${{ matrix.build_context }}
          keep_versions: 10
          package: ${{ matrix.package }}
          tag: demo
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    needs: [builds]
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.deployer.yml@v0.8.2
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      environment: dev
      tag: demo
      triggers: ('backend/' 'frontend/' 'migrations/')
      params:
        --set global.secrets.persist=false

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always() && (!failure()) && (!cancelled())
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Success!"
